name: CLI only
on:
  push:
    branches: [ main, master ]
    paths:
      - "app/**"
      - ".github/workflows/cli-only.yml"
  pull_request:
    branches: [ main, master ]
    paths:
      - "app/**"
      - ".github/workflows/cli-only.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
        with:
          toolchain: "1.90.0"
      - name: Build (CLI only)
        run: cargo build -p app --bin app --features admin_debug,subs_http,reqwest --locked
      - name: Clippy (deny warnings)
        run: cargo clippy -p app -- -D warnings
      - name: Test (minimal)
        run: cargo test -p app --lib -- --quiet
