name: concurrency-smoke

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  loom-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: Run loom smoke tests (sb-core, app)
        env:
          RUSTFLAGS: --cfg loom
        run: |
          cargo test -q -p sb-core -- tests loom
          cargo test -q -p app -- tests loom

  miri-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly + miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - uses: Swatinem/rust-cache@v2
      - name: Run miri on targeted crates
        run: |
          cargo miri test -q -p sb-core --lib || true
          cargo miri test -q -p app --lib || true
