name: coverage-and-mutants

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage-smoke:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
        with:
          components: clippy
      - name: Install llvm-tools (for cargo-llvm-cov)
        run: rustup component add llvm-tools-preview || true
      - name: Run coverage script
        run: scripts/test/cov.sh || true

  mutants-smoke:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: Run cargo-mutants smoke
        run: scripts/test/mutants-smoke.sh || true
