name: supply-chain

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check

  msrv-minver-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          components: clippy
          override: true
      - name: Install nightly (for -Z minimal-versions)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: false
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Minimal versions update
        run: cargo +nightly update -Z minimal-versions
      - name: Workspace check (MSRV)
        run: cargo check --workspace --all-targets
