name: feature-matrix

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        preset: [minimal, metrics, router, full]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.79.0
          components: clippy
          override: true
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo check (preset)
        shell: bash
        run: |
          case "${{ matrix.preset }}" in
            minimal)
              cargo check -p app --no-default-features --features minimal ;;
            metrics)
              cargo check -p app --no-default-features --features observe ;;
            router)
              cargo check -p app --no-default-features --features router ;;
            full)
              cargo check -p app --no-default-features --features full ;;
          esac
      - name: Smoke tests
        if: matrix.os != 'ubuntu-latest' || always()
        shell: bash
        run: |
          set -e
          case "${{ matrix.preset }}" in
            minimal)
              cargo test -p app --no-default-features --features minimal --test cli_smoke -- minimal_help_and_version ;;
            metrics)
              cargo test -p app --no-default-features --features observe --test cli_smoke -- metrics_export_probe ;;
            router)
              cargo test -p app --no-default-features --features router --test cli_smoke -- router_route_explain_smoke ;;
            full)
              cargo test -p app --no-default-features --features full --test cli_smoke -- router_route_explain_smoke ;;
          esac
