name: preflight

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'preflight')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: Run preflight
        run: scripts/preflight.sh
      - name: Upload preflight artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preflight-artifacts
          path: |
            dist/**/*
            target/release/*
