name: release

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.preflight.outputs.digest }}
      signature: ${{ steps.preflight.outputs.signature }}
      rust-version: ${{ steps.preflight.outputs.rust-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: Run preflight checks
        id: preflight
        run: |
          bash scripts/tools/preflight.sh
          echo "digest=$(sha256sum target/preflight-report.json | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "signature=$(sha256sum target/preflight-report.json | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "rust-version=$(cargo version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_OUTPUT

  release-draft:
    needs: preflight
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: Add target
        if: matrix.target != ''
        run: rustup target add ${{ matrix.target }} || true
      - name: Build (release)
        run: |
          cargo build --release --bins --target ${{ matrix.target }}
      - name: Verify preflight consistency
        run: |
          echo "Verifying preflight digest: ${{ needs.preflight.outputs.digest }}"
          echo "Verifying rust version: ${{ needs.preflight.outputs.rust-version }}"
          # Verify consistent rust version
          current_rust=$(cargo version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          if [[ "$current_rust" != "${{ needs.preflight.outputs.rust-version }}" ]]; then
            echo "Error: Rust version mismatch. Preflight: ${{ needs.preflight.outputs.rust-version }}, Current: $current_rust"
            exit 1
          fi
      - name: Prepare package
        shell: bash
        run: |
          set -eux
          NAME="singbox-rust"
          TARGET="${{ matrix.target }}"
          OUT="dist/${NAME}-${TARGET}"
          mkdir -p "$OUT/bin" "$OUT/share/man" "$OUT/share/completions" "$OUT/LICENSES" || true
          # pick main binary name (singbox-rust or app)
          BIN_PATH="target/${TARGET}/release/singbox-rust"
          if [[ ! -f "$BIN_PATH" ]]; then BIN_PATH="target/${TARGET}/release/app"; fi
          cp "$BIN_PATH" "$OUT/bin/"
          # generate completions/man if supported
          if "$BIN_PATH" gen-completions --dir "$OUT/share/completions" >/dev/null 2>&1; then echo ok; fi
          if "$BIN_PATH" man --dir "$OUT/share/man" >/dev/null 2>&1; then echo ok; fi
          # copy docs and licenses
          cp README.md "$OUT/" || true
          cp LICENSE "$OUT/" || true
          cp LICENSES/THIRD-PARTY.md "$OUT/LICENSES/" || true
          # version info
          echo "version,$(git describe --tags --always || echo 0.0.0)" > "$OUT/VERSION.txt"
          # preflight digest
          echo "preflight_digest,${{ needs.preflight.outputs.digest }}" >> "$OUT/VERSION.txt"
          # archive
          mkdir -p dist
          if [[ "${{ matrix.archive }}" == "zip" ]]; then
            (cd dist && zip -r "${NAME}-${TARGET}.zip" "${NAME}-${TARGET}")
            shasum -a 256 "dist/${NAME}-${TARGET}.zip" > "dist/${NAME}-${TARGET}.zip.sha256"
          else
            tar -C dist -czf "dist/${NAME}-${TARGET}.tar.gz" "${NAME}-${TARGET}"
            shasum -a 256 "dist/${NAME}-${TARGET}.tar.gz" > "dist/${NAME}-${TARGET}.tar.gz.sha256"
          fi
      - name: Upload Release (draft)
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*
