name: release

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-draft:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust-setup
      - name: Add target
        if: matrix.target != ''
        run: rustup target add ${{ matrix.target }} || true
      - name: Build (release)
        run: |
          cargo build --release --bins --target ${{ matrix.target }}
      - name: Prepare package
        shell: bash
        run: |
          set -eux
          NAME="singbox-rust"
          TARGET="${{ matrix.target }}"
          OUT="dist/${NAME}-${TARGET}"
          mkdir -p "$OUT/bin" "$OUT/share/man" "$OUT/share/completions" || true
          # pick main binary name (singbox-rust or app)
          BIN_PATH="target/${TARGET}/release/singbox-rust"
          if [[ ! -f "$BIN_PATH" ]]; then BIN_PATH="target/${TARGET}/release/app"; fi
          cp "$BIN_PATH" "$OUT/bin/"
          # generate completions/man if supported
          if "$BIN_PATH" gen-completions --dir "$OUT/share/completions" >/dev/null 2>&1; then echo ok; fi
          if "$BIN_PATH" man --dir "$OUT/share/man" >/dev/null 2>&1; then echo ok; fi
          # copy docs
          cp README.md "$OUT/" || true
          cp LICENSE "$OUT/" || true
          # version info
          echo "version,$(git describe --tags --always || echo 0.0.0)" > "$OUT/VERSION.txt"
          # archive
          mkdir -p dist
          if [[ "${{ matrix.archive }}" == "zip" ]]; then
            (cd dist && zip -r "${NAME}-${TARGET}.zip" "${NAME}-${TARGET}")
            shasum -a 256 "dist/${NAME}-${TARGET}.zip" > "dist/${NAME}-${TARGET}.zip.sha256"
          else
            tar -C dist -czf "dist/${NAME}-${TARGET}.tar.gz" "${NAME}-${TARGET}"
            shasum -a 256 "dist/${NAME}-${TARGET}.tar.gz" > "dist/${NAME}-${TARGET}.tar.gz.sha256"
          fi
      - name: Upload Release (draft)
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*
